onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - bufferutil
  - prisma
  - utf-8-validate

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@<6.14.1: '>=6.14.1'
