name: docker

on:
  push:
    # branches:
    #   - "main"
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        project: [web, server]
        include:
          # include adds properties to matrix configurations that match (and dont override anything)
          # so the first "project: web" include only adds to the 'web' configuration, as there is only 1 dimension
          - project: web
            context: ./web
            image: ${{ vars.IMAGE_NAME_WEB }}

          - project: server
            context: ./server
            image: ${{ vars.IMAGE_NAME_SERVER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # name=,enable=true
          flavor: latest=false
          images: |
            ${{ vars.DOCKER_REGISTRY != '' && format('{0}/', vars.DOCKER_REGISTRY) || '' }}${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch,suffix=-{{sha}}

        # add commit timestamp to ${{ env }}, from event timestamp if available in event
        # otherwise get timestamp from git (for workflow_dispatch)
      - name: Extract Git metadata
        run: |
          export timestamp=${{ github.event.head_commit.timestamp }}
          export COMMIT_TIME=$([ -n "$timestamp" ] && echo $timestamp || git log -1 --pretty=%aI)
          echo "COMMIT_TIME=$COMMIT_TIME" >> $GITHUB_ENV
        # if: github.github.event_name == 'workflow_dispatch'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.project }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ${{ matrix.context }}
          # docker-metadata annotations see https://github.com/opencontainers/image-spec/blob/main/annotations.md
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
          # github.event.head_commit.timestamp is only set on push event, not worflow_dispatch
          # for workflow_dispatch: fetch commit using API? https://docs.github.com/de/rest/commits/commits?apiVersion=2022-11-28#get-a-commit
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            BUILD_TIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            COMMIT_SHA=${{ github.sha }}
            COMMIT_TIME=${{ env.COMMIT_TIME }}
          # COMMIT_TIME=${{ github.event.head_commit.timestamp || env.COMMIT_TIME }}
