name: docker

on:
  push:
    # branches:
    #   - "main"
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        project: [web, server]
        include:
          # include adds properties to matrix configurations that match (and dont override anything)
          # so the first "project: web" include only adds to the 'web' configuration, as there is only 1 dimension
          - project: web
            context: ./web
            image: ${{ vars.IMAGE_NAME_WEB }}

          - project: server
            context: ./server
            image: ${{ vars.IMAGE_NAME_SERVER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # name=,enable=true
          flavor: latest=false
          images: |
            ${{ vars.DOCKER_REGISTRY != '' && format('{0}/', vars.DOCKER_REGISTRY) || '' }}${{ matrix.image }}
          tags: |
            type=ref,event=branch,suffix=-{{ github.sha | slice(0, 7) }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

          # type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.project }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ${{ matrix.context }}

  # server:
  #   runs-on: ubuntu-latest
  #   env:
  #     IMAGE_NAME: ${{ vars.IMAGE_NAME_SERVER }}

  #   steps:
  #     - name: Extract Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v4
  #       with:
  #         # name=,enable=true
  #         images: |
  #           ${{ vars.DOCKER_REGISTRY != '' && format('{0}/', vars.DOCKER_REGISTRY) || '' }}${{ env.IMAGE_NAME }}
  #         tags: |
  #           type=ref,event=branch
  #           type=semver,pattern={{major}}.{{minor}}
  #           type=semver,pattern={{major}}.{{minor}}.{{path}}

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ vars.DOCKER_REGISTRY }}
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
